// personal-budget-react/src/HomePage/HomePage.js
import axios from 'axios';
import React, { useEffect, useState } from 'react';
import Chart from 'chart.js/auto';
import * as d3 from 'd3';

function HomePage() {

    const [budgetData, setBudgetData] = useState([]);
    var dataSource = {
        datasets: [
          {
            data: [],
            backgroundColor: [
              '#ffcd56',
              '#ff6384',
              '#36a2eb',
              '#fd6b19',
              '#F0F8FF',
              '#FFFACD',
              '#B22222'
            ],
          },
        ],
        labels: [],
      };

    const fetchData = async () => {
        
        axios.get('/db.json')
        .then( (res) => {
            for (var i = 0; i < res.data.myBudget.length; i++) {
                dataSource.datasets[0].data[i] = res.data.myBudget[i].budget;
                dataSource.labels[i] = res.data.myBudget[i].title;
              }
            setBudgetData(res.data.myBudget);
            console.log(res.data.myBudget);
            createPieChart();
            donutChart(res.data.myBudget);
        } )
        .catch( (err) => {
            console.log( err );
        })
      };

    useEffect(() => {
        console.log("useEffect.!");
        fetchData();
    }, []);

    function createPieChart(){
        var ctx = document.getElementById("myChart").getContext("2d");
        var myPieChart = new Chart(ctx, {
            type: "pie",
            data: dataSource
        });        
    }

    const donutChart = (data) => {
        const width = 400;
        const height = 400;
        const radius = Math.min(width, height) / 2;
    
        const svg = d3.select('#donut-chart')
                      .append('svg')
                      .attr('width', width)
                      .attr('height', height)
                      .append('g')
                      .attr('transform', `translate(${width / 2},${height / 2})`);
    
        const color = d3.scaleOrdinal()
                        .domain(data.map(d => d.title))
                        .range(d3.schemeSet2);
    
        const pie = d3.pie()
                      .value(d => d.budget)
                      .sort(null);
    
        const arc = d3.arc()
                      .innerRadius(radius * 0.3)
                      .outerRadius(radius * 0.8);
    
        const outerArc = d3.arc()
                           .innerRadius(radius * 0.85)
                           .outerRadius(radius * 0.85);
    
        const arcs = svg.selectAll('arc')
                        .data(pie(data))
                        .enter()
                        .append('g')
                        .attr('class', 'arc');
    
        arcs.append('path')
            .attr('d', arc)
            .attr('fill', (d, i) => color(i))
            .attr('class', 'slice');
    
        // Add labels with lines only on left side of the chart
        arcs.filter(d => (d.endAngle + d.startAngle) / 2 < Math.PI)
            .append('text')
            .attr('transform', function(d) {
                const pos = outerArc.centroid(d);
                return 'translate(' + pos + ')';
            })
            .attr('dy', '.35em')
            .style('text-anchor', 'start')
            .text(d => d.data.title);
    
        arcs.filter(d => (d.endAngle + d.startAngle) / 2 < Math.PI)
            .append('polyline')
            .attr('stroke', 'black')
            .attr('stroke-width', 1)
            .attr('fill', 'none')
            .attr('points', function(d) {
                const pos = outerArc.centroid(d);
                return [arc.centroid(d), outerArc.centroid(d), pos];
            });
    
        // Add labels with lines only on right side of the chart
        arcs.filter(d => (d.endAngle + d.startAngle) / 2 >= Math.PI)
            .append('text')
            .attr('transform', function(d) {
                const pos = outerArc.centroid(d);
                pos[0] = pos[0] - 10; // Adjust indentation for right side labels
                return 'translate(' + pos + ')';
            })
            .attr('dy', '.35em')
            .style('text-anchor', 'end')
            .text(d => d.data.title);
    
        arcs.filter(d => (d.endAngle + d.startAngle) / 2 >= Math.PI)
            .append('polyline')
            .attr('stroke', 'black')
            .attr('stroke-width', 1)
            .attr('fill', 'none')
            .attr('points', function(d) {
                const pos = outerArc.centroid(d);
                pos[0] = pos[0] - 10; // Adjust indentation for right side lines
                return [arc.centroid(d), outerArc.centroid(d), pos];
            });
    
    };
    
    
    

    return (
        <main className="center" id="main">

            <div className="page-area">

                <article>
                    <h1>Stay on track</h1>
                    <p>
                        
                        <meta name="description" content="Tips for staying on track"/>
                        
                        <>
                            Do you know where you are spending your money? If you really stop to track it down,
                            you would get surprised! Proper budget management depends on real data... and this
                            app will help you with that!
                        </>
                    </p>
                </article>
        
                <article>
                    <h1>Alerts</h1>
                    <p>
                        
                        <span>
                            What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
                        </span>
                    </p>
                </article>
        
                <article>
                    <h1>Results</h1>
                    <p>
                        People who stick to a financial plan, budgeting every expense, get out of debt faster!
                        Also, they to live happier lives... since they expend without guilt or fear... 
                        because they know it is all good and accounted for.
                    </p>
                </article>
        
                <article>
                    
                    <header>
                        <h1> Free </h1>
                    </header>
                    <p>
                        This app is free!!! And you are the only one holding your data!
                    </p>
                </article>
        
                <article>
                    
                    <header>
                        <h2> Stay on track </h2>
                    </header>
                    
                    <h3>
                        Do you know where you are spending your money? If you really stop to track it down,
                        you would get surprised! Proper budget management depends on real data... and this
                        app will help you with that!
                    </h3>
                </article>
        
                <article>
                    <h1>Alerts</h1>
                    <p>
                        
                        <i>
                            What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
                        </i>
                    </p>
                </article>
        
                <article>
                    <h1>Results</h1>
                    <p>
                        People who stick to a financial plan, budgeting every expense, get out of debt faster!
                        Also, they to live happier lives... since they expend without guilt or fear... 
                        because they know it is all good and accounted for.
                    </p>
                </article>
        
                <article>
                    <h1>Chart</h1>
                    <p>
                        <canvas id="myChart" ></canvas>
                    </p>
                </article>
                
                <div>
                    <h1>D3.js</h1>
                    <svg id="donut-chart" style={{ height: 400, width: 450 }}></svg>
                </div>

            </div>
        </main>
    )
}

export default HomePage

// Downloads/personal-budget/personal-budget/src/app/homepage/homepage.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Chart } from 'chart.js/auto';
import * as d3 from 'd3';

import { DataService } from '../data.service';


@Component({
  selector: 'pb-homepage',
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.scss']
})
export class HomepageComponent implements OnInit{

    public dataSource: any;
    public chart: any;
    public svg: any;
    public pie: any;

    constructor( private http: HttpClient, private dataService: DataService ){}

    ngOnInit(): void {
        setTimeout(() => {
            this.dataSource = this.dataService.dataSource;
            this.createPieChart();
            this.createD3Chart();
          }, 1000);
    }

    createPieChart() {
        var ctx = document.getElementById('myChart') as HTMLCanvasElement;
        if( typeof ctx !== 'undefined' ){
            var myPieChart = new Chart(ctx, {
                type: 'pie',
                data: this.dataSource
            });
        }
    }

    private getData() {
        const arr = [];
        const labels = this.dataSource.labels;
        for (let i = 0; i < this.dataSource.datasets[0].data.length; i++) {
            arr.push({
                label: labels[i],
                value: this.dataSource.datasets[0].data[i],
            });
        }
        return arr;
    }

    private midAngle(d: { startAngle: number; endAngle: number; }) {
        return d.startAngle + (d.endAngle - d.startAngle) / 2;
    }

    createD3Chart(){
        const width = 600;
        const height = 300;
        this.svg = d3.select('svg')
               .attr('width', width)
               .attr('height', height)
               .append('g')
               .attr('transform', 'translate(' + width / 2 + ',' +
                height / 2 + ')');

        let radius = Math.min(width, height) / 2 ;

        let color = d3.scaleOrdinal()
            .domain(this.dataSource.labels)
           .range(['#ffcd56',
           '#ff6384',
           '#36a2eb',
           '#fd6b19',
           '#33FF57',
           '#33FFFF',
           '#FF33FF',"#98abc5", "#8a89a6", "#7b6888", "#6b486b", "#a05d56", "#d0743c", "#ff8c00"]);

        this.pie = d3.pie()
        .sort(null)
                   .value((d: any) => d.value);
        let dataReady = this.pie(this.getData());

        let arc = d3.arc()
                   .innerRadius(radius * 0.4)
                   .outerRadius(radius * 0.8);
        let outerArc = d3.arc()
                   .innerRadius(radius * 0.9)
                   .outerRadius(radius * 0.9);
                   this.svg
                   .selectAll('allSlices')
                   .data(dataReady)
                   .enter()
                   .append('path')
                   .attr('d', arc)
                   .attr('fill', (d:any) => (color(d.data.label)))
                   .attr('stroke', 'white')
                   .style('stroke-width', '2px')
                   .style('opacity', 0.7);
        this.svg
                   .selectAll('allPolylines')
                   .data(dataReady)
                   .enter()
                   .append('polyline')
                     .attr('stroke', 'black')
                     .style('fill', 'none')
                     .attr('stroke-width', 1)
                     .attr('points', (d:any) => {
                         const posA = arc.centroid(d);
                         const posB = outerArc.centroid(d);
                         const posC = outerArc.centroid(d);
                         posC[0] = radius * 0.95 * (this.midAngle(d) < Math.PI ? 1 : -1);
                         return [posA, posB, posC];
                       });
                       this.svg
                       .selectAll('allLabels')
                       .data(dataReady)
                       .enter()
                       .append('text')
                         .text( (d:any) => { console.log(d.data.label); return d.data.label; } )
                         .attr('transform', (d:any) => {
                             const pos = outerArc.centroid(d);
                             pos[0] = radius * 0.99 * (this.midAngle(d) < Math.PI ? 1 : -1);
                             return 'translate(' + pos + ')';
                           })
                         .style('text-anchor', (d:any) => {
                             return (this.midAngle(d) < Math.PI ? 'start' : 'end');
                           });

    }
}

<main class="center" id="main">

    <div class="page-area">

        

        <pb-article>
            <h1>Stay on track</h1>
            <p>
                    Do you know where you are spending your money? If you really stop to track it down,
                    you would get surprised! Proper budget management depends on real data... and this
                    app will help you with that!
        </pb-article>

        <pb-article>
            <h1>Alerts</h1>
            <p>
                    What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
            </p>
        </pb-article>

        <pb-article>
            <h1>Results</h1>
            <p>
                People who stick to a financial plan, budgeting every expense, get out of debt faster!
                Also, they to live happier lives... since they expend without guilt or fear...
                because they know it is all good and accounted for.
            </p>
        </pb-article>

        <pb-article>
            <h1> Free </h1>
            <p>
                This app is free!!! And you are the only one holding your data!
            </p>
        </pb-article>

        <pb-article>
            <!-- This is an SEO Change -->
            <h2> Stay on track </h2>
            <h3>
                Do you know where you are spending your money? If you really stop to track it down,
                you would get surprised! Proper budget management depends on real data... and this
                app will help you with that!
            </h3>
        </pb-article>

        <pb-article>
            <h1>Alerts</h1>
            <p>
                    What if your clothing budget ended? You will get an alert. The goal is to never go over the budget.
            </p>
        </pb-article>

        <pb-article>
            <h1>Results</h1>
            <p>
                People who stick to a financial plan, budgeting every expense, get out of debt faster!
                Also, they to live happier lives... since they expend without guilt or fear...
                because they know it is all good and accounted for.
            </p>
        </pb-article>

        <article>
            <h1>Chart</h1>
            <p>
                <canvas id="myChart" width="400" height="400"></canvas>
            </p>
        </article>
        <article>
            <h1>D3.js</h1>
            <p>
                <svg id="donut"></svg>
            </p>
        </article>
    </div>

</main>
